/* 
 * The MIT License
 *
 * Copyright 2019 G.K #gkexxt@outlook.com.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package javadm.ui;

import javadm.com.Download;
import javax.swing.JOptionPane;

/**
 *
 * @author gkalianan
 */
public class OptionMenu extends javax.swing.JDialog {

    private final Download selectedDownload;
    private final boolean isNewDownload;
    private final DownloadManager dm;

    /**
     * Creates new OptionDialog
     *
     * @param downloadManager
     * @param download
     * @param modal
     * @param isNewdownload
     */
    public OptionMenu(DownloadManager downloadManager, Download download, boolean modal, boolean isNewdownload) {
        super(downloadManager, modal);
        this.dm = downloadManager;
        this.isNewDownload = isNewdownload;
        this.selectedDownload = download;

        if (isNewDownload) {
            initComponents();
            btnRemove.setVisible(false);
            btnSave.setVisible(false);
            txtDirectory.setText(dm.getSetting().getDirectory());
            SpinConnNCount.setValue(dm.getSetting().getConnectionCount());
            txtuagent.setText(dm.getSetting().getUserAgent());
            cburl.setSelected(true);
            cbAuto.setSelected(dm.getSetting().isAutoStart());
            setTitle("New Download");

        } else {
            initComponents();
            cbAuto.setVisible(false);
            btnOK.setEnabled(!selectedDownload.isComplete());
            btnSave.setEnabled(!selectedDownload.isComplete());
            setTitle("Download Option");

        }

        //txtName.setEditable(false);
        this.setLocation(dm.getLocation().x - (this.getWidth() - dm.getWidth()) / 2, dm.getLocation().y - (this.getHeight() - dm.getHeight()) / 2);

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        cburl = new javax.swing.JCheckBox();
        txtUrl = new javax.swing.JTextField();
        cbname = new javax.swing.JCheckBox();
        txtName = new javax.swing.JTextField();
        cbdir = new javax.swing.JCheckBox();
        txtDirectory = new javax.swing.JTextField();
        cbUagent = new javax.swing.JCheckBox();
        btnDirectory = new javax.swing.JButton();
        txtuagent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SpinConnNCount = new javax.swing.JSpinner();
        cbAuto = new javax.swing.JCheckBox();
        btnRemove = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jCheckBox3.setText("URL");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(setBorderTitile()

        ));

        cburl.setText("URL");
        cburl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cburlStateChanged(evt);
            }
        });

        txtUrl.setText(selectedDownload.getUrl());
        txtUrl.setEnabled(false);

        cbname.setText("Name");
        cbname.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbnameStateChanged(evt);
            }
        });

        txtName.setText(selectedDownload.getName());
        txtName.setEnabled(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        cbdir.setText("Directory");
        cbdir.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbdirStateChanged(evt);
            }
        });

        txtDirectory.setText(selectedDownload.getDirectory());
        txtDirectory.setEnabled(false);

        cbUagent.setText("User Agent");
        cbUagent.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbUagentStateChanged(evt);
            }
        });

        btnDirectory.setText("Select");
        btnDirectory.setEnabled(false);
        btnDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectoryActionPerformed(evt);
            }
        });

        txtuagent.setText(selectedDownload.getUserAgent());
        txtuagent.setEnabled(false);

        jLabel4.setText("Connections");

        SpinConnNCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        SpinConnNCount.setValue(selectedDownload.getConnections());

        cbAuto.setText("Auto Start");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbname, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbdir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUagent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cburl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtuagent)
                            .addComponent(txtName)
                            .addComponent(txtUrl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinConnNCount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbAuto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cburl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbdir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDirectory)
                    .addComponent(txtDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbUagent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinConnNCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAuto))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnRemove.setText("Remove");
        btnRemove.setFocusPainted(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.setMinimumSize(new java.awt.Dimension(40, 33));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(btnRemove)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnCancel)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        updateData();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectoryActionPerformed
        // TODO add your handling code here:
        txtDirectory.setText(dm.chooseFolder());
    }//GEN-LAST:event_btnDirectoryActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        new RemoveMenu(dm, true);
        this.dispose();


    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if (updateData()) {
            this.dispose();
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cbUagentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbUagentStateChanged
        // TODO add your handling code here:
        txtuagent.setEnabled(cbUagent.isSelected());
    }//GEN-LAST:event_cbUagentStateChanged

    private void cbdirStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbdirStateChanged
        // TODO add your handling code here:
        txtDirectory.setEnabled(cbdir.isSelected());
        btnDirectory.setEnabled(cbdir.isSelected());
    }//GEN-LAST:event_cbdirStateChanged

    private void cbnameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbnameStateChanged
        // TODO add your handling code here:
        txtName.setEnabled(cbname.isSelected());
    }//GEN-LAST:event_cbnameStateChanged

    private void cburlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cburlStateChanged
        // TODO add your handling code here:
        txtUrl.setEnabled(cburl.isSelected());
    }//GEN-LAST:event_cburlStateChanged

    private String setBorderTitile() {

        if (isNewDownload) {
            return "New Download";
        } else {
            return selectedDownload.getName();
        }
    }

    private boolean updateData() {

        String url = txtUrl.getText().trim();
        String fname;
        if (txtName.getText().isBlank()) {
            fname = selectedDownload.getUrl_name(url);
        } else {
            fname = txtName.getText();
        }

        String directory = txtDirectory.getText().trim();
        txtName.setText(fname);
        try {

            if (directory.isBlank() || url.isBlank() || txtuagent.getText().isBlank()) {
                throw new IllegalArgumentException("blank fields");
            } else if (!selectedDownload.isUrlOK(url)) {
                throw new IllegalArgumentException("invalid url");
            } else if (!txtName.isEditable() && txtName.getText().isBlank()) {
                txtName.setEditable(true);
                throw new IllegalArgumentException("unable parse filename input manually");
            } else if (txtName.isEditable() && txtName.getText().isBlank()) {
                throw new IllegalArgumentException("field file name is blank");
            } else {
                selectedDownload.setConnections((int) SpinConnNCount.getValue());
                selectedDownload.setUrl(url);
                selectedDownload.setDirectory(txtDirectory.getText());
                selectedDownload.setName(txtName.getText());
                selectedDownload.setUserAgent(txtuagent.getText());
                if (isNewDownload) {
                    dm.addDownload(selectedDownload, cbAuto.isSelected());
                } else {
                    dm.updateDownload(selectedDownload);

                }
            }
        } catch (Exception e) {
            dm.showInfo("Error update download \n" + e.getMessage(), "JavaDM",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinConnNCount;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDirectory;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbAuto;
    private javax.swing.JCheckBox cbUagent;
    private javax.swing.JCheckBox cbdir;
    private javax.swing.JCheckBox cbname;
    private javax.swing.JCheckBox cburl;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDirectory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtuagent;
    // End of variables declaration//GEN-END:variables
}
