/* 
 * The MIT License
 *
 * Copyright 2019 G.K #gkexxt@outlook.com.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package javadm.ui;

import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javadm.com.DaoSqlite;
import javadm.com.Download;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;

/**
 *
 * @author gkalianan
 */
public class SchedulerMenu extends javax.swing.JDialog {

    /**
     * Creates new form SchedulerMenu
     *
     */
    //private JSpinner spinner;
    private Download download;

    public SchedulerMenu(DownloadManager dm, boolean modal, Download download) {
        super(dm, modal);
        this.download = download;

        initComponents();

        try {
            spStart.setValue(Download.FORMATTER.parse(download.getScheduleStart()));
            cbStart.setEnabled(true);
            cbStart.setSelected(true);

        } catch (Exception ex) {
            //Logger.getLogger(SchedulerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            spStop.setValue(Download.FORMATTER.parse(download.getScheduleStop()));
            cbStop.setEnabled(true);
            cbStop.setSelected(true);
        } catch (Exception ex) {
            //Logger.getLogger(SchedulerMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        cbActive.setEnabled(!download.isComplete());
        cbActive.setSelected(!download.isComplete() && download.isScheduled());
        cbStart.setEnabled(cbActive.isSelected());
        cbStop.setEnabled(cbActive.isSelected());
        btnOK.setEnabled(!download.isComplete());

        this.setLocation(dm.getLocation().x + (dm.getWidth() - this.getWidth()) / 2, dm.getLocation().y + (dm.getHeight() - this.getHeight()) / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbStart = new javax.swing.JCheckBox();
        spStart = new javax.swing.JSpinner();
        cbStop = new javax.swing.JCheckBox();
        spStop = new javax.swing.JSpinner();
        cbActive = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scheduler");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Schedule : "+download.getName()));

        cbStart.setText("Start");
        cbStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbStartStateChanged(evt);
            }
        });

        spStart.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spStart.setEnabled(false);

        cbStop.setText("Stop");
        cbStop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbStopStateChanged(evt);
            }
        });

        spStop.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spStop.setEnabled(false);

        cbActive.setText("Active");
        cbActive.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbActiveStateChanged(evt);
            }
        });
        cbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbStart)
                        .addComponent(cbStop, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spStop)
                        .addComponent(spStart))
                    .addComponent(cbActive))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbActive)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStart)
                .addGap(15, 15, 15)
                .addComponent(spStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbActive.getAccessibleContext().setAccessibleDescription("");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbStartStateChanged
        // TODO add your handling code here:
        spStart.setEnabled(cbStart.isSelected());
    }//GEN-LAST:event_cbStartStateChanged

    private void cbStopStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbStopStateChanged
        // TODO add your handling code here:
        spStop.setEnabled(cbStop.isSelected());
    }//GEN-LAST:event_cbStopStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:

        if (cbStart.isSelected()) {
            download.setScheduleStart(Download.FORMATTER.format((Date) spStart.getValue()));
        } else {
            download.setScheduleStart(null);
        }
        if (cbStop.isSelected()) {
            download.setScheduleStop(Download.FORMATTER.format((Date) spStop.getValue()));
        } else {
            download.setScheduleStop(null);
        }
        
        download.setScheduled(cbActive.isSelected());
        

        DaoSqlite db = new DaoSqlite();
        db.updateDownload(download);
        this.dispose();

    }//GEN-LAST:event_btnOKActionPerformed

    private void cbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActiveActionPerformed

    private void cbActiveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbActiveStateChanged
        // TODO add your handling code here:
        cbStart.setEnabled(cbActive.isSelected());
        cbStop.setEnabled(cbActive.isSelected());
    }//GEN-LAST:event_cbActiveStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox cbActive;
    private javax.swing.JCheckBox cbStart;
    private javax.swing.JCheckBox cbStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spStart;
    private javax.swing.JSpinner spStop;
    // End of variables declaration//GEN-END:variables
}
